from __future__ import annotations

from .rtl_config import LOADER_MAX_PROGRAM_SIZE

REGISTER_START = "===REGISTERS_START==="
REGISTER_END = "===REGISTERS_END==="
MEMORY_START = "===MEMORY_START==="
MEMORY_END = "===MEMORY_END==="
VGA_START = "===VGA_START==="
VGA_END = "===VGA_END==="
SIMULATION_TIMEOUT_MARKER = "===SIMULATION_TIMEOUT==="


def _render(template: str, **values: object) -> str:
    for name, value in values.items():
        template = template.replace(f"@{name}@", str(value))
    return template


_LOADER_TEMPLATE = """module Loader
    import cpu_pkg::*;
#(
    parameter DATA_WIDTH = 8,
    parameter ADDR_WIDTH = 24,
    parameter MAX_PROGRAM_SIZE = cpu_pkg::LOADER_MAX_PROGRAM_SIZE
)(
    input  logic clock,
    input  logic reset,

    output logic        write_ram = 1'b0,
    output logic [(DATA_WIDTH-1):0]  data_in_ram = '0,
    output logic [ADDR_WIDTH-1:0] write_addr_ram = '0,
    output logic        loader_done = 1'b0
);
    (* ramstyle = \"M20K\" *)
    logic [(DATA_WIDTH-1):0] program_mem [0:MAX_PROGRAM_SIZE-1];

    initial begin
        for (int i = 0; i < MAX_PROGRAM_SIZE; i++) begin
            program_mem[i] = 8'h00;
        end

@PROGRAM_BYTES@    end

    typedef enum logic [1:0] {IDLE, LOAD, DONE} state_t;
    state_t st = IDLE;

    // One extra bit is required to represent PROGRAM_SIZE itself when an
    // image fills a power-of-two address space exactly.
    logic [ADDR_WIDTH:0] load_addr = '0;

    localparam int PROGRAM_SIZE = @PROGRAM_SIZE@;

    initial begin
        if (PROGRAM_SIZE > MAX_PROGRAM_SIZE)
            $fatal(1, "Runtime program is %0d bytes; loader capacity is %0d", PROGRAM_SIZE, MAX_PROGRAM_SIZE);
        if (PROGRAM_SIZE > (2**ADDR_WIDTH))
            $fatal(1, "Runtime program is %0d bytes; address space is %0d", PROGRAM_SIZE, 2**ADDR_WIDTH);
    end

    always_ff @(posedge clock or posedge reset) begin
        if (reset) begin
            st             <= IDLE;
            load_addr      <= '0;
            write_ram      <= 1'b0;
            data_in_ram    <= '0;
            write_addr_ram <= '0;
            loader_done    <= 1'b0;
        end else begin
            case (st)
                IDLE: begin
                    if (USE_INIT_FILE) begin
                        loader_done <= 1'b1;
                        st          <= DONE;
                    end else begin
                        st <= LOAD;
                    end
                end

                LOAD: begin
                    if (load_addr < PROGRAM_SIZE) begin
                        write_ram      <= 1'b1;
                        data_in_ram    <= program_mem[load_addr];
                        write_addr_ram <= load_addr[ADDR_WIDTH-1:0];
                        load_addr      <= load_addr + 1'b1;
                    end else begin
                        write_ram     <= 1'b0;
                        loader_done   <= 1'b1;
                        st            <= DONE;
                    end
                end

                DONE: begin
                    write_ram <= 1'b0;
                end
            endcase
        end
    end

endmodule
"""

_LOADER_PREFIX, _, _LOADER_REST = _LOADER_TEMPLATE.partition("@PROGRAM_BYTES@")
_LOADER_SIZE_PREFIX, _, _LOADER_SUFFIX = _LOADER_REST.partition("@PROGRAM_SIZE@")


def render_loader_sv(
    program_bytes: bytes,
    *,
    addr_width: int = 24,
    generated_by: str = "web runner",
    emit_loader_done: bool = False,
) -> str:
    if addr_width <= 0:
        raise ValueError("addr_width must be positive")
    capacity = min(LOADER_MAX_PROGRAM_SIZE, 1 << addr_width)
    if len(program_bytes) > capacity:
        raise ValueError(
            "Runtime program image is too large: "
            f"{len(program_bytes)} bytes including its halt word; maximum is {capacity}"
        )
    program_lines = "".join(
        f"        program_mem[{index:<3}] = 8'h{value:02X};\n"
        for index, value in enumerate(program_bytes)
    )
    result = (
        _LOADER_PREFIX + program_lines + _LOADER_SIZE_PREFIX
        + str(len(program_bytes)) + _LOADER_SUFFIX + "\n"
    )
    if addr_width != 24:
        result = result.replace("    parameter ADDR_WIDTH = 24,", f"    parameter ADDR_WIDTH = {addr_width},")
    if generated_by != "web runner":
        result = result.replace("generated by web runner", f"generated by {generated_by}")
    if emit_loader_done:
        result = result.replace(
            "                        loader_done   <= 1'b1;\n                        st            <= DONE;",
            "                        loader_done   <= 1'b1;\n"
            '                        $display("LOADER_DONE at %0t (1ps)", $time);\n'
            "                        st            <= DONE;",
        )
    return result


_RUNTIME_LOADER_TEMPLATE = """module Loader
    import cpu_pkg::*;
#(
    parameter DATA_WIDTH = 8,
    parameter ADDR_WIDTH = 24,
    parameter MAX_PROGRAM_SIZE = cpu_pkg::LOADER_MAX_PROGRAM_SIZE
)(
    input  logic                    clock,
    input  logic                    reset,

    output logic                    write_ram = 1'b0,
    output logic [(DATA_WIDTH-1):0] data_in_ram = '0,
    output logic [ADDR_WIDTH-1:0]   write_addr_ram = '0,
    output logic                    loader_done = 1'b0
);
    logic [(DATA_WIDTH-1):0] program_mem [0:MAX_PROGRAM_SIZE-1];
    integer program_size = 0;
    integer plusarg_ok = 0;

    // The compiled harness is shared by every request: each invocation gets an
    // isolated directory with its own program.hex and passes the image size as
    // a plusarg, so nothing here needs recompiling per program.
    initial begin
        for (int i = 0; i < MAX_PROGRAM_SIZE; i++) begin
            program_mem[i] = '0;
        end

        plusarg_ok = $value$plusargs("PROGRAM_SIZE=%d", program_size);
        if (!plusarg_ok)
            $fatal(1, "Missing +PROGRAM_SIZE plusarg");
        if (program_size <= 0)
            $fatal(1, "Runtime program size must be positive");
        if (program_size > MAX_PROGRAM_SIZE)
            $fatal(1, "Runtime program is %0d bytes; loader capacity is %0d",
                   program_size, MAX_PROGRAM_SIZE);
        if (program_size > (2**ADDR_WIDTH))
            $fatal(1, "Runtime program is %0d bytes; address space is %0d",
                   program_size, 2**ADDR_WIDTH);

        if (program_size > 0 && program_size <= MAX_PROGRAM_SIZE
                && program_size <= (2**ADDR_WIDTH))
            $readmemh("program.hex", program_mem, 0, program_size - 1);
    end

    typedef enum logic [1:0] {IDLE, LOAD, DONE} state_t;
    state_t st = IDLE;
    logic [ADDR_WIDTH:0] load_addr = '0;

    always_ff @(posedge clock or posedge reset) begin
        if (reset) begin
            st             <= IDLE;
            load_addr      <= '0;
            write_ram      <= 1'b0;
            data_in_ram    <= '0;
            write_addr_ram <= '0;
            loader_done    <= 1'b0;
        end else begin
            case (st)
                IDLE: begin
                    if (USE_INIT_FILE) begin
                        loader_done <= 1'b1;
                        st          <= DONE;
                    end else begin
                        st <= LOAD;
                    end
                end

                LOAD: begin
                    if (load_addr < program_size) begin
                        write_ram      <= 1'b1;
                        data_in_ram    <= program_mem[load_addr];
                        write_addr_ram <= load_addr[ADDR_WIDTH-1:0];
                        load_addr      <= load_addr + 1'b1;
                    end else begin
                        write_ram   <= 1'b0;
                        loader_done <= 1'b1;
                        st          <= DONE;
                    end
                end

                DONE: write_ram <= 1'b0;
            endcase
        end
    end
endmodule
"""


def render_runtime_loader_sv(*, addr_width: int = 24) -> str:
    if addr_width <= 0:
        raise ValueError("addr_width must be positive")
    result = _RUNTIME_LOADER_TEMPLATE
    if addr_width != 24:
        result = result.replace(
            "    parameter ADDR_WIDTH = 24,",
            f"    parameter ADDR_WIDTH = {addr_width},",
        )
    return result + "\n"


_RUNTIME_TB_TEMPLATE = """`timescale 1ns/1ps

module @MODULE_NAME@;
    reg clock = 1'b0;
    reg [3:0] KEY = 4'b1111;
    wire [9:0] LEDR;
    wire [6:0] HEX0, HEX1, HEX2, HEX3, HEX4, HEX5;
    localparam int DATA_WIDTH = @DATA_WIDTH@;
    localparam int ADDR_WIDTH = @ADDR_WIDTH@;
    localparam real clock_period = 0.2;

    integer mem_start = 0;
    integer mem_end = 0;
    integer max_cycles = 0;
    integer key_mask = 0;
    integer plusarg_ok = 0;
    integer cycles;
    integer addr;

    CPU #(
        .DATA_WIDTH(DATA_WIDTH),
        .ADDR_WIDTH(ADDR_WIDTH),
        .USE_SLOW_CLOCK(0),
        .CLOCK_FREQ_HZ(1)
    ) dut (
        .clock(clock),
        .KEY(KEY),
        .LEDR(LEDR),
        .HEX0(HEX0),
        .HEX1(HEX1),
        .HEX2(HEX2),
        .HEX3(HEX3),
        .HEX4(HEX4),
        .HEX5(HEX5)
    );

    initial begin
        forever #(clock_period/2) clock = ~clock;
    end

    initial begin
        plusarg_ok = $value$plusargs("MEM_START=%d", mem_start);
        if (!plusarg_ok) $fatal(1, "Missing +MEM_START plusarg");
        plusarg_ok = $value$plusargs("MEM_END=%d", mem_end);
        if (!plusarg_ok) $fatal(1, "Missing +MEM_END plusarg");
        plusarg_ok = $value$plusargs("MAX_CYCLES=%d", max_cycles);
        if (!plusarg_ok) $fatal(1, "Missing +MAX_CYCLES plusarg");
        plusarg_ok = $value$plusargs("KEY_MASK=%d", key_mask);
        if (!plusarg_ok) $fatal(1, "Missing +KEY_MASK plusarg");

        if (mem_start < 0 || mem_end < mem_start || mem_end >= (2**ADDR_WIDTH))
            $fatal(1, "Invalid memory range %0d..%0d", mem_start, mem_end);
        if (max_cycles <= 0)
            $fatal(1, "MAX_CYCLES must be positive");
        if (key_mask < 0 || key_mask > 15)
            $fatal(1, "KEY_MASK must be in 0..15");
        KEY = (~key_mask) & 4'hF;

        cycles = 0;
        while (!dut.halted && cycles < max_cycles) begin
            @(posedge clock);
            cycles = cycles + 1;
        end
        if (!dut.halted) begin
            $display("@SIMULATION_TIMEOUT_MARKER@");
            $display("ERROR: Simulation timeout - CPU did not halt");
            $finish;
        end

        $display("@REGISTER_START@");
        for (int i = 0; i < 15; i++) begin
            if (^dut.data_out_registers[i] === 1'bX)
                $display("R%0d=X", i);
            else
                $display("R%0d=%0d (0x%h)", i, dut.data_out_registers[i], dut.data_out_registers[i]);
        end
        if (^dut.data_out_pc === 1'bX) $display("PC=X");
        else $display("PC=%0d (0x%h)", dut.data_out_pc, dut.data_out_pc);
        if (^dut.data_out_ledr === 1'bX) $display("LE=X");
        else $display("LE=%0d (0x%h)", dut.data_out_ledr, dut.data_out_ledr);
        if (^dut.data_out_hex === 1'bX) $display("HEX=X");
        else $display("HEX=%0d (0x%h)", dut.data_out_hex, dut.data_out_hex);
        if (^dut.data_out_cpsr === 1'bX) $display("CPSR=X");
        else $display("CPSR=0x%h", dut.data_out_cpsr);
        // Vector and accumulator files; counts match NPU_VREGS and NPU_ACCS.
        for (int i = 0; i < 8; i++)
            $display("Q%0d=%0d (0x%h)", i, dut.executer.vreg[i], dut.executer.vreg[i]);
        for (int i = 0; i < 4; i++)
            $display("A%0d=%0d (0x%h)", i, $signed(dut.executer.acc_file[i]),
                     dut.executer.acc_file[i]);
        $display("@REGISTER_END@");

        $display("@MEMORY_START@");
        for (addr = mem_start; addr <= mem_end; addr = addr + 1) begin
            if (^dut.storage.ram[addr] === 1'bX)
                $display("M[%0d]=X", addr);
            else
                $display("M[%0d]=%0d (0x%h)", addr, dut.storage.ram[addr], dut.storage.ram[addr]);
        end
        $display("@MEMORY_END@");

        $display("@VGA_START@");
        for (addr = 0; addr < cpu_pkg::VGA_FB_SIZE; addr = addr + 1) begin
            if (^dut.fb_inst.fb_mem[addr] === 1'bX)
                $display("VGA[%0d]=X", addr);
            else if (dut.fb_inst.fb_mem[addr] != 8'h00)
                $display("VGA[%0d]=%0d (0x%h)", addr, dut.fb_inst.fb_mem[addr], dut.fb_inst.fb_mem[addr]);
        end
        $display("@VGA_END@");
        $finish;
    end
endmodule
"""


def render_runtime_testbench(
    module_name: str,
    addr_width: int,
    data_width: int,
) -> str:
    if addr_width <= 0 or data_width <= 0:
        raise ValueError("addr_width and data_width must be positive")
    return _render(
        _RUNTIME_TB_TEMPLATE,
        MODULE_NAME=module_name,
        DATA_WIDTH=data_width,
        ADDR_WIDTH=addr_width,
        REGISTER_START=REGISTER_START,
        REGISTER_END=REGISTER_END,
        MEMORY_START=MEMORY_START,
        MEMORY_END=MEMORY_END,
        VGA_START=VGA_START,
        VGA_END=VGA_END,
        SIMULATION_TIMEOUT_MARKER=SIMULATION_TIMEOUT_MARKER,
    ) + "\n"
